spring.jpa.hibernate.ddl-auto=update
logging.level.com.scoutplay=INFO
app.cookie.secure=true
server.forward-headers-strategy=framework
server.error.include-message=never
spring.jpa.open-in-view=false
app.cookie.same-site=Strict
